GoormBbang/CloudBread_server

build.gradle, src/main/java/com/cloudbread/global/config/SwaggerConfig.java, src/main/resources/application.yml
- close #1 
- Swagger API 를 추가했습니다
- localhost:8080/ url로 접속하면 아래와 같은 swagger 문서를 볼 수 있습니다.
- 다만, localhost에서의 swagger api를 적용했습니다
=> [chore/#1] : swagger api 추가 (일단 jwt 인증 방식 채택)

.gitignore, build.gradle
- issue #2 
- oauth2 구현 전에 민감한 정보를 담을 application-secret.yml 파일을 .gitignore 파일에 추가했습니다.
=> chore/#2 : .gitignore에 application-secret.yml 추가

src/main/java/com/cloudbread/auth/jwt/JwtUtil.java
=> [chore/#14] : 테스트PR

src/main/java/com/cloudbread/domain/user/api/UserRestController.java, src/main/java/com/cloudbread/domain/user/application/UserService.java, src/main/java/com/cloudbread/domain/user/application/UserServiceImpl.java, src/main/java/com/cloudbread/domain/user/converter/UserConverter.java, src/main/java/com/cloudbread/domain/user/domain/entity/User.java, src/main/java/com/cloudbread/domain/user/domain/repository/UserAllergyRepository.java, src/main/java/com/cloudbread/domain/user/domain/repository/UserDietRepository.java, src/main/java/com/cloudbread/domain/user/domain/repository/UserHealthRepository.java, src/main/java/com/cloudbread/domain/user/dto/UserResponseDto.java, src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
=> [feat#19] : 내 정보 조회

build.gradle, src/main/java/com/cloudbread/domain/food/domain/Food.java, src/main/java/com/cloudbread/domain/food/domain/FoodNutrient.java, src/main/java/com/cloudbread/domain/food/domain/Nutrient.java, src/main/java/com/cloudbread/domain/food/enums/NutrientType.java, src/main/java/com/cloudbread/domain/food/enums/Unit.java, src/main/java/com/cloudbread/domain/food/repository/FoodNutrientRepository.java, src/main/java/com/cloudbread/domain/food/repository/FoodRepository.java, src/main/java/com/cloudbread/domain/food/repository/NutrientRepository.java, src/main/java/com/cloudbread/global/config/SecurityConfig.java, src/main/java/com/cloudbread/global/db_seeder/food/FoodDataSeedController.java, src/main/java/com/cloudbread/global/db_seeder/food/FoodDataSeedService.java, src/main/java/com/cloudbread/global/db_seeder/food/FoodSeedDto.java, src/main/java/com/cloudbread/global/db_seeder/food/ResetMode.java, src/main/java/com/cloudbread/global/db_seeder/user/UserDataSeeder.java, src/main/resources/application.yml
- close #20 
- 엑셀파일을 업로드하면 food 데이터가 쌓여요
- foods, nutrients, food_nutrients 총 3개의 테이블에 값이 쌓입니다.
=> [Feat/#20] food 데이터 쌓기

src/main/java/com/cloudbread/auth/oauth2/OAuth2LoginSuccessHandler.java, src/main/java/com/cloudbread/auth/token/api/TokenRestController.java, src/main/java/com/cloudbread/auth/token/application/TokenService.java, src/main/java/com/cloudbread/auth/token/domain/Token.java, src/main/java/com/cloudbread/auth/token/domain/TokenRepository.java, src/main/java/com/cloudbread/auth/token/dto/TokenRequestDto.java, src/main/java/com/cloudbread/auth/token/dto/TokenResponseDto.java, src/main/java/com/cloudbread/auth/token/exception/RefreshTokenNotFoundException.java, src/main/java/com/cloudbread/auth/token/exception/TokenUnauthorizedException.java, src/main/java/com/cloudbread/domain/user/api/UserRestController.java, src/main/java/com/cloudbread/domain/user/application/UserService.java, src/main/java/com/cloudbread/domain/user/application/UserServiceImpl.java, src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java, src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java, src/main/java/com/cloudbread/global/config/SecurityConfig.java
- close #24 
- 리프레시토큰 재발급, 로그아웃 api 
자세한 내용은 swagger api 캡쳐본을 확인해주세요!
https://www.notion.so/Swagger-API-27386831418c80b3b150ccd568d07241
=> [Feat/#24] 로그아웃 리프레시토큰 재발급 api

src/main/java/com/cloudbread/domain/user/api/UserRestController.java, src/main/java/com/cloudbread/domain/user/application/UserService.java, src/main/java/com/cloudbread/domain/user/application/UserServiceImpl.java, src/main/java/com/cloudbread/domain/user/converter/UserConverter.java, src/main/java/com/cloudbread/domain/user/domain/entity/User.java, src/main/java/com/cloudbread/domain/user/domain/repository/AllergyRepository.java, src/main/java/com/cloudbread/domain/user/domain/repository/DietTypeRepository.java, src/main/java/com/cloudbread/domain/user/domain/repository/HealthTypeRepository.java, src/main/java/com/cloudbread/domain/user/dto/UserRequestDto.java, src/main/java/com/cloudbread/domain/user/dto/UserResponseDto.java, src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
- close #22 
설정화면-내 정보 조회 api 수정 및 내 정보 수정 기능 작업 완료
설정 화면에서의 내 정보 조회 기능이 name만 받는게 아닌 id+name을 둘다 받고, 설정 화면에서의 내 정보 수정 기능이 작업 완료됨
=> [feat/#22] 내 정보 조회 수정&내 정보 수정

src/main/java/com/cloudbread/domain/user/api/UserRestController.java, src/main/java/com/cloudbread/domain/user/application/UserService.java, src/main/java/com/cloudbread/domain/user/application/UserServiceImpl.java, src/main/java/com/cloudbread/domain/user/converter/UserConverter.java, src/main/java/com/cloudbread/domain/user/domain/entity/User.java, src/main/java/com/cloudbread/domain/user/dto/UserRequestDto.java, src/main/java/com/cloudbread/domain/user/dto/UserResponseDto.java
- close #31 
내 정보 수정 기능
메인화면에서의 내 정보 수정(이름/생년월일)
=> [feat/#31] 사용자 정보 수정(메인)

src/main/java/com/cloudbread/domain/user/api/UserRestController.java, src/main/java/com/cloudbread/domain/user/application/UserService.java, src/main/java/com/cloudbread/domain/user/application/UserServiceImpl.java, src/main/java/com/cloudbread/domain/user/domain/entity/User.java, src/main/java/com/cloudbread/domain/user/exception/UserAlreadyDeactivatedException.java, src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java, src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
- close #33 
회원 탈퇴 기능
- 회원 탈퇴 기능
- 설정/내정보수정시 생년월일 null값 -> 생년월일 제외로 변경
=> [Feat/#33] 회원탈퇴

src/main/java/com/cloudbread/domain/food/domain/entity/Food.java, src/main/java/com/cloudbread/global/db_seeder/food/FoodDataSeedService.java
- close #41 
Food.name ← 엑셀의 “식품명” 컬럼
Food.category ← 엑셀의 “식품대분류명” 컬럼
=> [Feat/#41] 음식 데이터 수정

src/main/java/com/cloudbread/domain/crawling/application/CrawlingService.java, src/main/java/com/cloudbread/domain/crawling/domain/repository/TipContentRepository.java, src/main/java/com/cloudbread/domain/tip/api/UserTipController.java, src/main/java/com/cloudbread/domain/tip/application/UserTipService.java, src/main/java/com/cloudbread/domain/tip/application/UserTipServiceImpl.java, src/main/java/com/cloudbread/domain/user/application/UserService.java, src/main/java/com/cloudbread/domain/user/application/UserServiceImpl.java, src/main/java/com/cloudbread/domain/user/dto/UserResponseDto.java
- close #39 
메인화면-이번주차팁(전체/태아/임산부/건강) 조회
메인화면-이번주차팁(전체/태아/임산부/건강) 조회
=> [feat/#39] 이번주차팁 전체/태아/임산부/영양 조회 작업 완료

build.gradle, src/main/java/com/cloudbread/global/db_seeder/food/FoodDataSeedService.java
- close #43 
- food 데이터 엑셀표 업로드 방식 바꿈
- java memory out 에러 떠서, SAXHelper 를 이용
=> [feat/#43] : 배포서버, food 데이터 시더 해결

src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
=> [fix] : pr 에러 수정

src/main/resources/application.yml
- 배포 서버, 로컬 서버를 위해 yaml 파일 옮기기
=> fix : yaml 파일 옮기기

src/main/resources/application-prod.yml
=> fix : ai 엔드포인트만 변경

src/main/java/com/cloudbread/domain/photo_analyses/api/PhotoAnalysisRestController.java, src/main/java/com/cloudbread/domain/photo_analyses/application/PhotoAnalysisService.java, src/main/java/com/cloudbread/domain/photo_analyses/application/PhotoAnalysisServiceImpl.java, src/main/java/com/cloudbread/domain/photo_analyses/domain/entity/PhotoAnalysis.java, src/main/java/com/cloudbread/domain/photo_analyses/dto/PhotoAnalysisRequest.java, src/main/java/com/cloudbread/domain/photo_analyses/dto/PhotoAnalysisResponse.java
- issue #47 
- 음식 후보 3개 중 1개 선택 (FE -> BE) api 추가했습니다
=> [feat/#47] :음식 후보 3개 중 1개 선택 (FE -> BE) api 추가

src/main/java/com/cloudbread/domain/food_history/api/FoodHistoryRestController.java, src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryService.java, src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryServiceImpl.java, src/main/java/com/cloudbread/domain/food_history/dto/FoodHistoryRequest.java, src/main/java/com/cloudbread/domain/food_history/dto/FoodHistoryResponse.java, src/main/java/com/cloudbread/domain/user/domain/entity/UserFoodHistory.java, src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
- close #58 
- 식단 추가 api 완료했습니다
=> [feat/#58] : 식단 추가 api

src/main/java/com/cloudbread/domain/food/domain/repository/FoodNutrientRepository.java, src/main/java/com/cloudbread/domain/nutrition/api/UserNutritionController.java, src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsService.java, src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsServiceImpl.java, src/main/java/com/cloudbread/domain/nutrition/dto/TodayNutrientsStatsDto.java, src/main/java/com/cloudbread/domain/nutrition/model/NutrientCalculationResult.java, src/main/java/com/cloudbread/domain/user/domain/repository/UserFoodHistoryRepository.java, src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
- close #51
오늘의 영양분석 조회 
- 식단 추가(POST /api/food-history) 후 오늘의 영양 분석 조회
=> [feat/#51] 오늘의 영양분석 조회

src/main/java/com/cloudbread/domain/food_history/api/FoodHistoryRestController.java, src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryService.java, src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryServiceImpl.java, src/main/java/com/cloudbread/domain/food_history/dto/DayMealCountDto.java, src/main/java/com/cloudbread/domain/food_history/dto/DayMealRecord.java, src/main/java/com/cloudbread/domain/food_history/dto/FoodHistoryCalendarDto.java, src/main/java/com/cloudbread/domain/user/domain/repository/UserFoodHistoryRepository.java, src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java, src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
- close #63 
캘린더 전체 조회
- 한달 단위로 먹은 음식이 있다면 3끼중 1개만 먹으면 점 1개, 2끼 먹으면 점 2개, 3끼 다 먹으면 점 3개
=> [feat/#63] 캘린더전체조회

src/main/java/com/cloudbread/domain/chat/nutrients/application/NutritionChatServiceImpl.java, src/main/java/com/cloudbread/domain/chat/nutrients/dto/ai/AiChatRequest.java, src/main/java/com/cloudbread/domain/food/domain/entity/Food.java
- close #67 
- 기존에 작성했던 챗봇 api에서 AI쪽으로 프록시할 때, 프롬포트 형식에서 Request Body 형식으로 변경
=> [fix/#67] : 영양분석 후 챗봇 api

src/main/java/com/cloudbread/domain/chat/main/api/AiGeneralChatRestController.java, src/main/java/com/cloudbread/domain/chat/main/application/AiGeneralChatService.java, src/main/java/com/cloudbread/domain/chat/main/application/AiGeneralChatServiceImpl.java, src/main/java/com/cloudbread/domain/chat/main/application/session_store/AiInMemorySessionStore.java, src/main/java/com/cloudbread/domain/chat/main/application/session_store/AiSessionContext.java, src/main/java/com/cloudbread/domain/chat/main/application/session_store/AiSessionStore.java, src/main/java/com/cloudbread/domain/chat/main/dto/AiGeneralChatRequestGen.java, src/main/java/com/cloudbread/domain/chat/main/dto/AiGeneralChatResponseGen.java, src/main/java/com/cloudbread/domain/chat/main/exception/InvalidTopicException.java, src/main/java/com/cloudbread/domain/chat/main/exception/MissingTopicException.java, src/main/java/com/cloudbread/domain/chat/nutrients/application/user_profile/UserProfileServiceImpl.java, src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java
- close #71 
- 챗봇 메인화면 세션 생성 및 QA api 구현 완료했습니다.
=> [Feat/#71] 챗봇 메인화면 api

src/main/java/com/cloudbread/domain/food/domain/repository/FoodNutrientRepository.java, src/main/java/com/cloudbread/domain/nutrition/api/UserNutritionController.java, src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsService.java, src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsServiceImpl.java, src/main/java/com/cloudbread/domain/nutrition/dto/TodayNutrientsStatsDto.java, src/main/java/com/cloudbread/domain/nutrition/dto/TodayNutrientsSummaryResponse.java, src/main/java/com/cloudbread/domain/nutrition/model/NutrientCalculationResult.java, src/main/java/com/cloudbread/domain/user/domain/repository/UserFoodHistoryRepository.java, src/main/java/com/cloudbread/domain/user/domain/repository/UserRepository.java, src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java, src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
=> [feat/70] 오늘의 영양 요약
